/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calc_volume;



/**
 *
 * @author michael.knudsen
 */
public class shapeBuilderGUI extends javax.swing.JFrame {

    /**
     * Creates new form shapeBuilderGUI
     */
    public shapeBuilderGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboShapeType = new javax.swing.JComboBox();
        lblSelector1 = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        txtWidth = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtRadius = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblVolume = new javax.swing.JLabel();
        lblSelector2 = new javax.swing.JLabel();
        lblFormulaDisplay = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblMyName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboShapeType.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        cboShapeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Box", "Cylinder", "Cone", "Sphere" }));
        cboShapeType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboShapeTypeItemStateChanged(evt);
            }
        });
        cboShapeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboShapeTypeActionPerformed(evt);
            }
        });
        cboShapeType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboShapeTypeFocusGained(evt);
            }
        });

        lblSelector1.setText("Please select the desired shape:");

        txtLength.setToolTipText("");
        txtLength.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Length: "));
        txtLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLengthActionPerformed(evt);
            }
        });

        txtWidth.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Width:"));

        txtHeight.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Height:"));

        txtRadius.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Radius (Cylinder, Cone, or Sphere):"));

        btnCalculate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnCalculate.setText("CALCULATE VOLUME");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblVolume.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VOLUME:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 0, 18))); // NOI18N

        lblSelector2.setText("(all values are in inches)");

        lblFormulaDisplay.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formula:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14)))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("RESET FORM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblMyName.setText("Michael Knudsen 2013 ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblSelector1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSelector2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cboShapeType, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblFormulaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)))
                                .addContainerGap(36, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(lblVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblMyName)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSelector1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSelector2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboShapeType, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRadius, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit))
                        .addGap(18, 18, 18)
                        .addComponent(lblFormulaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMyName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
  
        //Declare variables 
        double length = 0; 
        double width = 0; 
        double height = 0;
        double radius = 0; 
        double volume = 0; 
        int shapeIndexValue = cboShapeType.getSelectedIndex();
        
        //Get values from textbox entries: 
        
        
        
        
        if (shapeIndexValue == 0) {
            //BOX SHAPE
            length = Double.parseDouble(txtLength.getText()); 
            width = Double.parseDouble(txtWidth.getText());
            height = Double.parseDouble(txtHeight.getText()); 
            
            volume = height * length * width; 
            
            //volume = MyUtils.formatNum((float) volume, "#.##");
            //lblVolume.setText(Double.toString(volume));
        } else if (shapeIndexValue == 1) {
            //CYLINDER SHAPE
            height = Double.parseDouble(txtHeight.getText()); 
            radius = Double.parseDouble(txtRadius.getText());
          
            volume = Math.PI * radius * radius * height; 
            //lblVolume.setText(Double.toString(volume)); 
        } else if (shapeIndexValue == 2) {
            //CONE SHAPE 
            height = Double.parseDouble(txtHeight.getText()); 
            radius = Double.parseDouble(txtRadius.getText()); 
            
            volume = (Math.PI * radius * radius * height)/3f; 
             
            //lblVolume.setText(Double.toString(volume));
        } else if (shapeIndexValue == 3){
            //SPHERE SHAPE
         
            radius = Double.parseDouble(txtRadius.getText()); 
            
            volume = (4f/3f) * Math.PI * radius * radius * radius; 
            //
        } else {
            //nothing selected. Time for an error message. 
             lblVolume.setText("Try again.");
        }
        //display the volume
        
        lblVolume.setText(Double.toString(volume) + " cubic inches");
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void cboShapeTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboShapeTypeFocusGained
        // TODO add your handling code here:
        int shapeIndexDisplayValue = cboShapeType.getSelectedIndex();
        
        if (shapeIndexDisplayValue == 0) {
            lblFormulaDisplay.setText("Length * Width * Height");
        } else if (shapeIndexDisplayValue == 1) {
            lblFormulaDisplay.setText("Pi * radius * radius * height"); 
        } else if (shapeIndexDisplayValue == 2) {
            lblFormulaDisplay.setText("(Pi * radius * radius * height)/3");
        } else if (shapeIndexDisplayValue == 3){
            lblFormulaDisplay.setText("4/3 * Pi * radius * radius * radius"); 
        }
    }//GEN-LAST:event_cboShapeTypeFocusGained

    private void cboShapeTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboShapeTypeItemStateChanged
        // TODO add your handling code here:
        //adding helpful volume displays
        int shapeIndexDisplayValue = cboShapeType.getSelectedIndex();
        
        if (shapeIndexDisplayValue == 0) {
            lblFormulaDisplay.setText("Length * Width * Height");
        } else if (shapeIndexDisplayValue == 1) {
            lblFormulaDisplay.setText("Pi * radius * radius * height"); 
        } else if (shapeIndexDisplayValue == 2) {
            lblFormulaDisplay.setText("(Pi * radius * radius * height) divided by 3");
        } else if (shapeIndexDisplayValue == 3){
            lblFormulaDisplay.setText("4/3 * Pi * radius * radius * radius"); 
        }
    }//GEN-LAST:event_cboShapeTypeItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtLength.setText("");
        txtWidth.setText("");
        txtHeight.setText("");
        txtRadius.setText("");
        lblVolume.setText(""); 
        txtLength.requestFocusInWindow(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLengthActionPerformed

    private void cboShapeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboShapeTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboShapeTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shapeBuilderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shapeBuilderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shapeBuilderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shapeBuilderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shapeBuilderGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox cboShapeType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblFormulaDisplay;
    private javax.swing.JLabel lblMyName;
    private javax.swing.JLabel lblSelector1;
    private javax.swing.JLabel lblSelector2;
    private javax.swing.JLabel lblVolume;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtRadius;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables
}
